name: Deploy to Web Hosting via SFTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Install dependencies
    #  run: npm install # Or any other command to install dependencies

    - name: Deploy to web hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        protocol: ftps
        local-dir: ./www/
        remote-dir: /
        args: "--exclude '.git*'"


